### ISSUE TITLE
More documentation is wanted

### ISSUE THREAD

**Issue by adah1972** [vpand/icpp#3]
**Describe the bug**
The document is lacking, and it is difficult to start. There need to be installation steps.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Version 22.04 LTS

**Additional context**
After the Linux build steps, I find `icpp` under build/src/. However, although it starts, it fails to work. The interactions:

```
$ src/icpp
ICPP v0.1.1.255. Copyright (c) vpand.com.
Running C++ in anywhere like a script.
>>> #include <iostream>
>>> std::cout << "Hello\n";
/tmp/9ff57889.cc:1:10: fatal error: 'iostream' file not found
    1 | #include <iostream>
      |          ^~~~~~~~~~
1 error generated.
11:58:33 R - Failed to compile: ./icpp -w -O1 -c /tmp/9ff57889.cc -o /tmp/9ff57889.o -no-canonical-prefixes -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-#pragma-messages -Wno-unknown-argument -std=c++23 -I/home/adah/Programming/icpp/build/src/./../include/c++/v1 -nostdinc++ -nostdlib++ -target x86_64-unknown-linux-gnu -fprebuilt-module-path=/home/adah/Programming/icpp/build/src/./../include/linux/module -I/home/adah/Programming/icpp/build/src/./../include
```

**Comment by GeekNeo** [comment]
The newly built naked icpp of course doesn't work. It needs the include/lib related stuff. The simplest way to run your own version is to replace the binary in the official release package. If you want to run it in the build directory, you need to construct the directory layout like the release package.
e.g:
build:
---include
------hdr-related
---src
------icpp
---lib
------lib-related

**Comment by adah1972** [comment]
> The newly built naked icpp of course doesn't work. It needs the include/lib related stuff. The simplest way to run your own version is to replace the binary in the official release package. If you want to run it in the build directory, you need to construct the directory layout like the release package. e.g: build: ---include ------hdr-related ---src ------icpp ---lib ------lib-related

My bug report was on documentation. :-)

As a user, I want the stuff to be well documented. I have no ideas where I should copy the files to or what other stuff I should combine with. Anything apparent to you developers are probably not so to me.

**Comment by GeekNeo** [comment]
OK, I'll describe this in the next release.

**Comment by adah1972** [comment]
> OK, I'll describe this in the next release.

Next release? If it is not very complicated, just provide the instructions in README, please.

**Comment by adah1972** [comment]
So there is no way to build and install completely from source?...

Anyway, I built from source only because the table in README says Executable Binary is not yet available. Since it is available, I am not in hurry.
