### ISSUE TITLE
Add a motivation section

### ISSUE THREAD

**Issue by cyruscyliu** [vpand/icpp#8]
Hey, amazing job! I heavily use Python when I do pwning and reverse engineering. Can you convince me to use ICPP?

Otherwise, could you please summarize the benefits of ICPP in different use cases?

Thank you very much!

**Comment by GeekNeo** [comment]
Firstly, I think you should read the existing [docs](https://github.com/vpand/icpp/tree/main/doc), it'll tell you many basics about icpp.
